# Data path config
external_data_path: data_blobs/external/
interim_data_path: data_blobs/interim/
processed_data_path: data_blobs/processed/
raw_data_path: data_blobs/raw/cifar-10-batches-py
test_batch_name: test_batch

# Plotting config
n_samples: 5
fig_dims: [15, 15]

# Data config
image_dim: 32
n_labels: 10
n_batches: 5
classes: ["airplane", "automobile", "bird", "cat", "deer", "dog", "frog", "horse", "ship", "truck"]

# Logger config
log_dir_name: logs
data_log: data.log

# Model config
model_weights_dir: model_weights/
model_log_dir: model_logs/
